### ISSUE TITLE
rename command to 'git-ignore'

### ISSUE THREAD

**Issue by ph-hs** [Antrikshy/ignr.py#1]

**Comment by Antrikshy** [comment]
Sounds too generic to me, not to mention longer and therefore more tedious to type. Sure, it's not a feature people use _that_ often, but I specifically picked `ignr` because it's short _and_ unique. You can set an alias, though.

**Comment by ph-hs** [comment]
Sorry, I shoulda been clearer. If you rename this git-ignore, it is available in the regular git eco-system:  'git ingnore'

Refer - http://paulhammant.com/2016/08/15/introducing-git-size-command-and-visualization/

**Comment by Antrikshy** [comment]
Interesting. I didn't know about this.

I would consider it, but it's way too much work to rename it at this point.
